import { ResponsiveImage } from "./ResponsiveImage";
const steps = [
 {title:"Plan the launch",summary:"The game, audience, assets and a workable schedule.",question:"What happens first?",answer:"Send the game summary, artwork, current page and target date. We review what is ready, what is missing and where you need help. The brief sets out the work, budget and responsibilities.",result:"A written scope before work begins."},
 {title:"Prepare the audience",summary:"A landing page, email sequence and creative tests.",question:"What do you build before launch?",answer:"We give interested players a clear introduction to the game and a way to follow along. Signup flows and tracking are tested before traffic starts. Useful emails show gameplay and explain what is coming.",result:"A working prelaunch setup in your accounts."},
 {title:"Create the campaign",summary:"The page, rewards and ads telling the same story.",question:"How does the creative come together?",answer:"I write the campaign copy, design the graphics and prepare ad variants around your confirmed game information. We review the rewards and product details together, then check the page on the chosen platform.",result:"Approved creative and a paid advertising plan."},
 {title:"Launch & stay involved",summary:"Launch checks, advertising, emails and backer updates.",question:"What happens during the live campaign?",answer:"We follow the agreed launch checklist, manage the scoped advertising and support updates and recurring questions. The brief defines the support period. At the end, we hand over assets, reports and the next communication tasks.",result:"Live support with clear dates and owners."},
] as const;
function ProcessPreview({step}:{step:number}) {
 return <div className={`gf-process-preview gf-process-preview-${step} glass`} aria-label={`Illustrative example for step ${step+1}`}><div className="gf-process-preview-bar"><span>0{step+1} / 04</span><span>Illustrative example</span></div>
 {step===0?<div className="gf-brief-preview"><span className="gf-eyebrow">Your launch brief</span><h3>A cooperative card game</h3><p>Playable prototype. Artwork in progress. First Kickstarter campaign.</p><div className="gf-file-stack"><span><b aria-hidden="true">▧</b>Artwork &amp; sample cards</span><span><b aria-hidden="true">≡</b>Audience &amp; reward plan</span><span><b aria-hidden="true">▤</b>Dates, owners &amp; budget</span></div><span className="gf-preview-pill">Scope agreed together</span></div>:null}
 {step===1?<div className="gf-email-preview"><div className="gf-email-top"><span>Prelaunch email draft</span><span aria-hidden="true">↗</span></div><ResponsiveImage src="/images/campaign/party-cards.webp" alt="Bright party card concept illustrating a prelaunch email" width="1200" height="800" loading="lazy"/><div><span className="gf-eyebrow">For people who signed up</span><h3>Meet the game.</h3><p>A quick look at the cards, a sample round and a date to come back for.</p><span className="gf-preview-pill">See how it plays ↗</span></div></div>:null}
 {step===2?<div className="gf-final-preview"><ResponsiveImage src="/images/campaign/adventure-cards.webp" alt="Retro science fiction card game concept used in a campaign creative example" width="1200" height="800" loading="lazy"/><div className="gf-preview-sections"><span>Meet the game <b aria-hidden="true">✓</b></span><span>How it plays <b aria-hidden="true">✓</b></span><span>Choose a reward <b aria-hidden="true">✓</b></span><span>Ad variants <b aria-hidden="true">✓</b></span></div><p>Copy and graphics reviewed before publishing</p></div>:null}
 {step===3?<div className="gf-brief-preview"><span className="gf-eyebrow">Launch day checklist</span><h3>Ready when the campaign opens.</h3><ul><li>Campaign page &amp; rewards checked</li><li>Launch email approved</li><li>Ads reviewed against the spend limit</li><li>Backer update drafted</li><li>Reporting &amp; next review scheduled</li></ul><span className="gf-preview-pill">Named owners. Agreed support dates.</span></div>:null}
 </div>;
}
export function CampaignProcess() {
 return <section className="gf-process-shell"><div className="gf-section gf-process" id="process" aria-labelledby="process-title"><div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">From preparation to launch</span><h2 id="process-title">See the work{" "}<br/><em>at each stage.</em></h2></div><p>A broader engagement follows these stages. If you only need one part, we fit it around the work you already have.</p></div><div className="gf-process-demo" data-reveal>{steps.map((s,i)=><details name="campaign-process" open={i===0} className="gf-process-step" key={s.title}><summary><span className="gf-process-step-number">0{i+1}</span><div><h3>{s.title}</h3><p>{s.summary}</p></div><span className="gf-process-step-arrow" aria-hidden="true">↗</span></summary><div className="gf-process-step-body"><strong>{s.question}</strong><p>{s.answer}</p><p className="gf-process-result">{s.result}</p></div><ProcessPreview step={i}/></details>)}</div><div className="gf-process-bottom"><p>Examples show the type of work involved. The brief confirms your deliverables.</p><a className="gf-text-link" href="#start-project">Talk through your project <span aria-hidden="true">↗</span></a></div></div></section>;
}
