const steps = [
 {title:"Send me your game",summary:"A short description, artwork and your launch plans.",question:"What do I need to send?",answer:"The game idea, a link to artwork you can share, your platform and planned launch date. Tell me which pieces are still in progress.",result:"You can start with the files you have. We’ll identify anything missing for the full page."},
 {title:"See your free mockup",summary:"An opening section to review before you book.",question:"What will I see?",answer:"A design for the opening of your campaign, using your artwork. It gives you a first look at the layout, colours and how the game is introduced.",result:"The mockup is free. You decide whether you’d like to book the full campaign."},
 {title:"Agree the $975 brief",summary:"The sections, output files and schedule in writing.",question:"What happens before payment?",answer:"We agree the page sections, graphics, review process, file formats and schedule. The campaign design price is $975 USD. New illustration, video and advertising are separate.",result:"You know what the project covers and what needs to be ready before work starts."},
 {title:"Review the full campaign",summary:"Copy, game graphics and rewards brought together.",question:"What happens before launch?",answer:"I write the copy and design the page. We review the product details and rewards together, then check the presentation in your chosen platform, including on a phone.",result:"You receive the files agreed in the brief and review the page before publishing."},
] as const;
function ProcessPreview({step}:{step:number}) {
 return <div className={`gf-process-preview gf-process-preview-${step} glass`} aria-label={`Illustrative example for step ${step+1}`}>
  <div className="gf-process-preview-bar"><span>0{step+1} / 04</span><span>Illustrative example</span></div>
  {step===0?<div className="gf-brief-preview"><span className="gf-eyebrow">Your project</span><h3>A party card game</h3><p>Artwork ready. Rewards being finalised. Kickstarter launch planned.</p><div className="gf-file-stack"><span><b aria-hidden="true">▧</b>Box &amp; card artwork</span><span><b aria-hidden="true">≡</b>How the game plays</span><span><b aria-hidden="true">▤</b>Reward contents</span></div><span className="gf-preview-pill">Ready to explore a direction</span></div>:null}
  {step===1?<div className="gf-opening-preview"><img src="/images/campaign/party-cards.webp" alt="Snack Attack party card concept used to illustrate an opening mockup" width="1200" height="800" loading="lazy"/><div><span className="gf-eyebrow">Opening mockup</span><h3>Your artwork.<br />A first layout to review.</h3><p>Game introduction · Visual direction</p><span className="gf-preview-pill">Free to request</span></div></div>:null}
  {step===2?<div className="gf-brief-preview"><span className="gf-eyebrow">Agreed campaign brief</span><h3>$975 <small>USD</small></h3><ul><li>Page structure &amp; copy</li><li>Section &amp; component graphics</li><li>Reward comparisons</li><li>Stretch goal graphics where needed</li><li>File formats &amp; review schedule</li></ul><span className="gf-preview-pill">Confirmed before work begins</span></div>:null}
  {step===3?<div className="gf-final-preview"><img src="/images/campaign/party-cards.webp" alt="Card game concept used in an illustrative campaign layout" width="1200" height="800" loading="lazy"/><div className="gf-preview-sections"><span>Meet the game <b aria-hidden="true">✓</b></span><span>How it plays <b aria-hidden="true">✓</b></span><span>What’s in the box <b aria-hidden="true">✓</b></span><span>Choose your reward <b aria-hidden="true">✓</b></span></div><p>Reviewed together before launch</p></div>:null}
 </div>;
}
export function CampaignProcess() {
 return <section className="gf-section gf-process" id="process" aria-labelledby="process-title"><div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">How it works</span><h2 id="process-title">What happens<br /><em>after you get in touch?</em></h2></div><p>Start with the free mockup. Here’s what you send, what I put together and when we agree the full project.</p></div><div className="gf-process-demo" data-reveal>{steps.map((s,i)=><details name="campaign-process" open={i===0} className="gf-process-step" key={s.title}><summary><span className="gf-process-step-number">0{i+1}</span><div><h3>{s.title}</h3><p>{s.summary}</p></div><span className="gf-process-step-arrow" aria-hidden="true">↗</span></summary><div className="gf-process-step-body"><strong>{s.question}</strong><p>{s.answer}</p><p className="gf-process-result">{s.result}</p></div><ProcessPreview step={i}/></details>)}</div><div className="gf-process-bottom"><p>The visual example uses an original card game concept.</p><a className="gf-text-link" href="#start-project">Send me your game <span aria-hidden="true">↗</span></a></div></section>;
}
