import Link from "next/link";
import {PastWork,ClientTestimonials} from "./PastWork";
import {MockupGallery} from "./MockupGallery";
import {Breadcrumbs,SeoHeader,SeoFooter} from "./SeoChrome";
import {JsonLd} from "./JsonLd";
import {absoluteUrl} from "../site-config";
import {campaignService} from "../seo-entities";
import {campaignDate,campaignFaqs,categoryFaqs,gameCategories} from "../campaign-content";
export type CampaignPage = {slug:string;title:string;description:string;headline:string;accent:string;image:string;alt:string;introTitle:string;intro:string;details:readonly string[];secondTitle:string;secondCopy:string;guide:string;guideTitle:string};
export function CampaignServicePage({page}:{page:CampaignPage}){const faqs=[...(categoryFaqs[page.slug]??[]),...campaignFaqs];return <>
 <JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":absoluteUrl(`/${page.slug}`),name:page.title,url:absoluteUrl(`/${page.slug}`),description:page.description,dateModified:campaignDate,isPartOf:{"@id":absoluteUrl("/#website")},inLanguage:"en",mainEntity:{"@id":absoluteUrl("/campaign-design#service")},breadcrumb:{"@id":absoluteUrl(`/${page.slug}#breadcrumb`)}},campaignService(),{"@type":"BreadcrumbList","@id":absoluteUrl(`/${page.slug}#breadcrumb`),itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:page.title,item:absoluteUrl(`/${page.slug}`)}]},{"@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}]}}/>
 <a className="skip-link" href="#service-content">Skip to content</a><SeoHeader/><main className="gf-service" id="service-content"><Breadcrumbs items={[{label:"Home",href:"/"},{label:page.title}]}/><section className="gf-service-hero"><div><span className="gf-eyebrow">Campaign design · $975 USD</span><h1>{page.headline}{" "}<br /><em>{page.accent}</em></h1><p>{page.description}</p><a className="gf-button" href="#start-project" data-analytics-event="service_interest" data-analytics-label="Free opening mockup" data-analytics-location={page.slug}>Get my free mockup <span aria-hidden="true">↗</span></a></div><div><img src={`/images/campaign/${page.image}.webp`} alt={page.alt} width={page.image==="hero"?1774:1000} height={page.image==="hero"?887:750} fetchPriority="high"/><p className="gf-caption">Concept mockup</p></div></section>
 <section className="gf-service-intro" data-reveal><h2>{page.introTitle}</h2><p>{page.intro}</p><ul>{page.details.map(d=><li key={d}>{d}</li>)}</ul><h2 style={{marginTop:40}}>{page.secondTitle}</h2><p>{page.secondCopy}</p><p>I write the copy and design the graphics from your artwork and project information. You review the work before launch. The brief sets out the deliverables and schedule for the $975 project.</p><p>Send a project summary and artwork link to request a free opening mockup. You can decide whether to book after you’ve seen it.</p><Link className="gf-text-link" href={`/guides/${page.guide}`}>{page.guideTitle} ↗</Link></section>
 {page.slug==="campaign-design"?<><PastWork/><ClientTestimonials/></>:null}{page.slug==="card-game-kickstarter-campaign-design"?<MockupGallery/>:null}
 <section className="gf-faq"><div><span className="gf-eyebrow">Campaign design FAQ</span><h2>Campaign design{" "}<br /><em>questions, answered.</em></h2></div><div>{faqs.map(f=><details key={f.question}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div></section><nav className="gf-service-related" aria-label="Campaign categories">{page.slug!=="campaign-design"?<Link href="/campaign-design">Full service &amp; $975 price ↗</Link>:null}{page.slug!=="gamefound-campaign-design"?<Link href="/gamefound-campaign-design">Gamefound page design ↗</Link>:null}{gameCategories.filter(g=>g.slug!==page.slug).map(g=><Link key={g.slug} href={`/${g.slug}`}>{g.name} ↗</Link>)}</nav></main><SeoFooter/>
 </>}
