import Link from "next/link";
import {Breadcrumbs,SeoHeader,SeoFooter} from "./SeoChrome";
import {JsonLd} from "./JsonLd";
import {absoluteUrl} from "../site-config";
import {campaignDate,campaignFaqs,gameCategories} from "../campaign-content";
export type CampaignPage = {slug:string;title:string;description:string;headline:string;accent:string;image:string;alt:string;introTitle:string;intro:string;details:readonly string[];secondTitle:string;secondCopy:string;guide:string;guideTitle:string};
export function CampaignServicePage({page}:{page:CampaignPage}){return <>
 <JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":absoluteUrl(`/${page.slug}`),name:page.title,url:absoluteUrl(`/${page.slug}`),description:page.description,dateModified:campaignDate,isPartOf:{"@id":absoluteUrl("/#website")},about:{"@id":absoluteUrl("/campaign-design#service")}},{"@type":"Service","@id":absoluteUrl("/campaign-design#service"),name:"Guildframe tabletop campaign design",serviceType:"Kickstarter and Gamefound campaign design",description:"Campaign structure, copy and graphics for tabletop crowdfunding projects.",provider:{"@id":absoluteUrl("/#organization")},url:absoluteUrl("/campaign-design"),offers:{"@type":"Offer",price:"975",priceCurrency:"USD",url:absoluteUrl("/campaign-design")}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:page.title,item:absoluteUrl(`/${page.slug}`)}]},{"@type":"FAQPage",mainEntity:campaignFaqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}]}}/>
 <a className="skip-link" href="#service-content">Skip to content</a><SeoHeader/><main className="gf-service" id="service-content"><Breadcrumbs items={[{label:"Home",href:"/"},{label:page.title}]}/><section className="gf-service-hero"><div><span className="gf-eyebrow">Campaign design · $975 USD</span><h1>{page.headline}<br /><em>{page.accent}</em></h1><p>{page.description}</p><a className="gf-button" href="#start-project">Get my free mockup <span aria-hidden="true">↗</span></a></div><div><img src={`/images/campaign/${page.image}.webp`} alt={page.alt} width="1000" height="750" fetchPriority="high"/><p className="gf-caption">Original concept artwork, not a client campaign.</p></div></section>
 <section className="gf-service-intro" data-reveal><h2>{page.introTitle}</h2><p>{page.intro}</p><ul>{page.details.map(d=><li key={d}>{d}</li>)}</ul><h2 style={{marginTop:40}}>{page.secondTitle}</h2><p>{page.secondCopy}</p><p>Guildframe combines your artwork and confirmed project information into campaign copy and graphics. You review the content before it goes live. We confirm the exact deliverables and schedule in the brief, so the $975 project has a clear finish line.</p><p>Request a free mockup with a project summary and a link to your artwork. It explores the opening section and gives you a useful first look at the direction, with no obligation to book.</p><Link className="gf-text-link" href={`/guides/${page.guide}`}>{page.guideTitle} ↗</Link></section>
 <section className="gf-faq"><div><span className="gf-eyebrow">Scope, price and the first step.</span><h2>Before<br /><em>we begin.</em></h2></div><div>{campaignFaqs.map(f=><details key={f.question}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div></section><nav className="gf-service-related" aria-label="Campaign categories">{gameCategories.filter(g=>g.slug!==page.slug).map(g=><Link key={g.slug} href={`/${g.slug}`}>{g.name} ↗</Link>)}</nav></main><SeoFooter/>
 </>}
