import Link from "next/link";
import { ResponsiveImage } from "./ResponsiveImage";

export const campaignJourney = [
  {title: "Plan the launch", summary: "Start with the game, the missing pieces and a realistic schedule.", supply: "Game summary, rules, artwork and target date.", receive: "A scope, schedule and clear responsibilities.", creator: "We have a playable prototype. Where do we start?", umair: "Send the rules, artwork and target date. I’ll map the work and what still needs preparing.", href: "/kickstarter-launch-services", link: "Launch planning"},
  {title: "Prepare the audience", summary: "Give interested players a place to sign up and a reason to come back.", supply: "Game details, account access and approvals.", receive: "A signup page, emails, tracking and creative tests.", creator: "How will players hear about the game?", umair: "I’ll prepare the signup page, emails and creative tests. We’ll agree the ad budget before anything runs.", href: "/kickstarter-prelaunch-marketing", link: "Prelaunch marketing"},
  {title: "Build the campaign", summary: "Show how the game plays and exactly what each reward includes.", supply: "Confirmed rewards, game facts and delivery details.", receive: "Campaign copy, graphics and ad creative.", creator: "Can players understand the game and choose a reward?", umair: "Here’s the page draft: gameplay, components, rewards and delivery details. Check the facts before we publish.", href: "/campaign-design", link: "Campaign design"},
  {title: "Launch and manage", summary: "Check the launch, run the agreed ads and keep backers informed.", supply: "Final approvals and agreed spend limits.", receive: "Ads management and scoped live support.", creator: "We’re ready to go live. What happens next?", umair: "We’ll check the page and launch email, manage the agreed ads, and prepare updates for your approval.", href: "/kickstarter-campaign-management", link: "Live campaign support"},
  {title: "Prepare the handoff", summary: "Organise the files and prepare the next backer communication.", supply: "Confirmed next steps and production updates.", receive: "Final assets, reports and agreed communications.", creator: "The campaign is over. What happens next?", umair: "Let’s prepare the next update, organise your final assets and confirm the handoff agreed in your scope.", href: "/post-campaign-support", link: "After the campaign"},
] as const;

function GameImage({priority = false, className = ""}: {priority?: boolean; className?: string}) {
  return <ResponsiveImage className={className} src="/images/campaign/party-cards.webp" sizes="(max-width: 699px) 240px, 310px" alt="Snack Attack, an original fictional party card game with colourful fruit cards" width="1200" height="800" loading={priority ? "eager" : "lazy"} fetchPriority={priority ? "high" : "auto"}/>;
}
function WindowBar({label}: {label: string}) {
  return <div className="gf-artifact-bar"><span className="gf-window-dots" aria-hidden="true"><i/><i/><i/></span><span>{label}</span></div>;
}
function StageArtifact({step, priority}: {step: number; priority: boolean}) {
  if (step === 0) return <div className="gf-artifact gf-artifact-brief"><WindowBar label="Launch brief"/><div className="gf-artifact-body"><span className="gf-artifact-kicker">The starting point</span><h4>Snack Attack</h4><GameImage priority={priority}/><div className="gf-brief-files"><span><i aria-hidden="true">▤</i> Rules &amp; sample cards</span><span><i aria-hidden="true">▧</i> Artwork folder</span><span><i aria-hidden="true">▦</i> Scope &amp; launch schedule</span></div><span className="gf-artifact-stamp">Agreed together <b aria-hidden="true">✓</b></span></div></div>;
  if (step === 1) return <div className="gf-artifact gf-artifact-signup"><WindowBar label="Your prelaunch page"/><GameImage priority={priority}/><div className="gf-artifact-body"><span className="gf-artifact-kicker">Snack Attack</span><h4>A little chaos.<br/>A lot of fruit.</h4><span className="gf-artifact-input">Your email address</span><span className="gf-artifact-button">Get the launch email <b aria-hidden="true">↗</b></span></div><div className="gf-email-slip"><span className="gf-mail-icon" aria-hidden="true">✉</span><div><b>Welcome to the table.</b><span>Your first game preview</span></div><span aria-hidden="true">✓</span></div></div>;
  if (step === 2) return <div className="gf-artifact gf-artifact-campaign"><WindowBar label="Campaign page draft"/><GameImage priority={priority}/><div className="gf-artifact-body"><span className="gf-artifact-kicker">Snack Attack</span><h4>Meet your next<br/>game night.</h4><div className="gf-campaign-sections"><span>How it plays <b aria-hidden="true">↘</b></span><div className="gf-sample-cards" aria-hidden="true"><i>★</i><i>✳</i><i>●</i></div><span>What’s in the box <b aria-hidden="true">↘</b></span><span>Choose your reward <b aria-hidden="true">↘</b></span></div><span className="gf-artifact-stamp">Copy + graphics <b aria-hidden="true">✓</b></span></div></div>;
  if (step === 3) return <div className="gf-artifact gf-artifact-launch"><WindowBar label="Launch checklist"/><div className="gf-artifact-body"><span className="gf-artifact-kicker">Before publishing</span><h4>Ready to go?</h4><ul className="gf-launch-checklist"><li><span aria-hidden="true">✓</span> Page &amp; rewards checked</li><li><span aria-hidden="true">✓</span> Launch email approved</li><li><span aria-hidden="true">✓</span> Ad spend limit agreed</li><li><span aria-hidden="true">✓</span> Backer update prepared</li></ul></div><div className="gf-ad-slip"><GameImage priority={priority}/><div><span>Ad creative preview</span><b>Bring a little chaos<br/>to game night.</b></div></div></div>;
  return <div className="gf-artifact gf-artifact-handoff"><WindowBar label="Your project files"/><div className="gf-artifact-body"><span className="gf-folder-icon" aria-hidden="true">▰</span><h4>All in one place.</h4><div className="gf-brief-files"><span><i aria-hidden="true">▧</i> Campaign creative</span><span><i aria-hidden="true">▥</i> Reports &amp; editable files</span><span><i aria-hidden="true">✉</i> Next backer update</span></div></div><div className="gf-update-slip"><span className="gf-artifact-kicker">Backer update draft</span><h5>Here’s what happens next.</h5><p>Production news. Next steps.<br/>The details you’ve confirmed.</p></div></div>;
}

/** These are illustrative conversations, not messages or results from a client. */
export function JourneyScene({step = 0, priority = false}: {step?: number; priority?: boolean}) {
  const stage = campaignJourney[step];
  return <figure className={`gf-journey-scene gf-journey-scene-${step}`} data-journey-scene aria-label={`Example project conversation: ${stage.title}`}>
    <div className="gf-scene-orbit" aria-hidden="true"/>
    <div className="gf-chat-phone"><div className="gf-phone-hardware" aria-hidden="true"><span>Guildframe</span><i/><span>▰</span></div><div className="gf-chat-header"><span className="gf-chat-avatar" aria-hidden="true">U</span><div><strong>Umair</strong><span>Your Guildframe project</span></div><span aria-hidden="true">⋯</span></div><div className="gf-chat-content"><span className="gf-chat-topic">{stage.title}</span><div className="gf-chat-bubble gf-chat-creator" data-chat-bubble><span>You</span><p>{stage.creator}</p></div><div className="gf-chat-bubble gf-chat-umair" data-chat-bubble><span>Umair</span><p>{stage.umair}</p></div><div className="gf-chat-attachment"><span aria-hidden="true">↗</span><span>{step === 0 ? "Launch brief" : step === 1 ? "Prelaunch drafts" : step === 2 ? "Campaign page draft" : step === 3 ? "Launch checklist" : "Project handoff"}<small>Attached to your project</small></span></div></div><div className="gf-chat-compose" aria-hidden="true"><span>Keep the project moving…</span><b>↑</b></div><div className="gf-phone-home" aria-hidden="true"/></div>
    <StageArtifact step={step} priority={priority}/>
    <figcaption>Example project conversation · Fictional card game</figcaption>
  </figure>;
}
export function CampaignProcess() {
  return <section className="gf-journey-shell" id="process" aria-labelledby="process-title"><div className="gf-journey-inner"><div className="gf-journey-heading" data-reveal><span className="gf-eyebrow">From the first brief to the final files</span><h2 id="process-title">Your campaign,<br/><em>step by step.</em></h2><p>One point of contact. A clear next step.<br/>Here’s how we work together.</p><Link href="/about" className="gf-journey-person"><span className="gf-chat-avatar" aria-hidden="true">U</span><span>Work directly with Umair <b aria-hidden="true">↗</b></span></Link></div>
    <ol className="gf-journey-track">{campaignJourney.map((stage, index) => <li className="gf-journey-stage" key={stage.title}><span className="gf-journey-marker" aria-hidden="true">0{index + 1}</span><div className="gf-journey-copy"><span className="gf-eyebrow">Stage 0{index + 1}</span><h3>{stage.title}</h3><p>{stage.summary}</p><dl><div><dt>You bring</dt><dd>{stage.supply}</dd></div><div><dt>I prepare</dt><dd>{stage.receive}</dd></div></dl><Link href={stage.href} className="gf-text-link">{stage.link} <span aria-hidden="true">↗</span></Link></div><JourneyScene step={index}/></li>)}</ol>
    <p className="gf-journey-end">Book one stage or bring the launch together. Your brief confirms the work and support period.</p>
  </div></section>;
}
