import Link from "next/link";
import {PastWork,ClientTestimonials} from "./PastWork";
import {MockupGallery} from "./MockupGallery";
import {Breadcrumbs,SeoHeader,SeoFooter} from "./SeoChrome";
import {JsonLd} from "./JsonLd";
import {absoluteUrl} from "../site-config";
import {campaignService,launchService} from "../seo-entities";
import {campaignDate,campaignFaqs,categoryFaqs,gameCategories} from "../campaign-content";
import {serviceCards} from "../launch-services";
export type CampaignPage = {slug:string;title:string;description:string;headline:string;accent:string;image:string;alt:string;introTitle:string;intro:string;details:readonly string[];secondTitle:string;secondCopy:string;guide:string;guideTitle:string;kind?:"launch"};
export function CampaignServicePage({page}:{page:CampaignPage}){
 const faqs=[...(categoryFaqs[page.slug]??[]),...campaignFaqs];
 const service=page.kind==="launch"?launchService(page.slug,page.title,page.description):campaignService(page.slug==="campaign-design");
 return <><JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":absoluteUrl(`/${page.slug}`),name:page.title,url:absoluteUrl(`/${page.slug}`),description:page.description,dateModified:campaignDate,isPartOf:{"@id":absoluteUrl("/#website")},inLanguage:"en",mainEntity:{"@id":service["@id"]},breadcrumb:{"@id":absoluteUrl(`/${page.slug}#breadcrumb`)}},service,{"@type":"BreadcrumbList","@id":absoluteUrl(`/${page.slug}#breadcrumb`),itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:page.title,item:absoluteUrl(`/${page.slug}`)}]},{"@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}]}}/>
 <a className="skip-link" href="#service-content">Skip to content</a><SeoHeader/><main className="gf-service" id="service-content"><Breadcrumbs items={[{label:"Home",href:"/"},{label:page.title}]}/><section className="gf-service-hero"><div><span className="gf-eyebrow">{page.kind==="launch"?"Tabletop launch services":"Campaign creative"}</span><h1>{page.headline}{" "}<br/><em>{page.accent}</em></h1><p>{page.description}</p><a className="gf-button" href="#start-project" data-analytics-event="service_interest" data-analytics-label={page.kind==="launch"?"Discuss my launch":"Free opening mockup"} data-analytics-location={page.slug}>{page.kind==="launch"?"Discuss my launch":"Get my free mockup"} <span aria-hidden="true">↗</span></a></div><div><img src={`/images/campaign/${page.image}.webp`} alt={page.alt} width={page.image==="hero"||page.image==="launch-studio"?1774:page.image==="party-cards"?1200:1000} height={page.image==="hero"||page.image==="launch-studio"?887:page.image==="party-cards"?800:750} fetchPriority="high"/><p className="gf-caption">Concept mockup</p></div></section>
 <section className="gf-service-intro" data-reveal><h2>{page.introTitle}</h2><p>{page.intro}</p><ul>{page.details.map(d=><li key={d}>{d}</li>)}</ul><h2 style={{marginTop:40}}>{page.secondTitle}</h2><p>{page.secondCopy}</p><p>Send your project summary, artwork link, current campaign and target date. We’ll agree the deliverables, fees, review process and schedule before work starts.</p><Link className="gf-text-link" href={`/guides/${page.guide}`}>{page.guideTitle} ↗</Link>{page.kind!=="launch"?<div className="gf-launch-cta"><h2>Need help beyond the page?</h2><p>Guildframe also handles prelaunch setup, email, paid advertising and live campaign support. You can keep an existing team in place and book the work you need.</p><Link className="gf-text-link" href="/kickstarter-launch-services">Explore the launch service ↗</Link></div>:null}</section>
 {page.slug==="campaign-design"?<section className="gf-service-pricing" id="pricing" aria-labelledby="design-price-title" data-reveal><span className="gf-eyebrow">Design on its own</span><h2 id="design-price-title">Campaign copy &amp; graphics</h2><div className="gf-price">$975 <span>USD / campaign</span></div><p>One Kickstarter or Gamefound campaign page using your supplied artwork. The brief confirms the page sections, campaign copy, graphics, reward comparisons, revision process and final files. Stretch goal graphics are included where agreed.</p><p>Paid advertising, prelaunch setup, live management, new illustration and video production are scoped separately. Request a free opening mockup before deciding.</p><a className="gf-button" href="#start-project">Request a free mockup ↗</a></section>:null}
 {page.slug==="kickstarter-launch-services"?<section className="gf-section"><div className="gf-section-heading"><h2>Explore each part of the launch.</h2></div><div className="gf-launch-service-grid">{serviceCards.map(s=><Link className="gf-launch-service-card glass" key={s.href} href={s.href}><span className="gf-eyebrow">{s.tag}</span><h3>{s.title}</h3><p>{s.copy}</p><span aria-hidden="true">↗</span></Link>)}</div><div className="gf-inline-links"><Link href="/gamefound-launch-services">Gamefound launch services ↗</Link><Link href="/post-campaign-support">Post-campaign support ↗</Link></div></section>:null}
 {page.slug==="campaign-design"||page.slug==="kickstarter-launch-services"?<><PastWork/><ClientTestimonials/></>:null}{page.slug==="card-game-kickstarter-campaign-design"?<MockupGallery/>:null}
 <section className="gf-faq"><div><span className="gf-eyebrow">Before you book</span><h2>Questions,{" "}<br/><em>answered.</em></h2></div><div>{faqs.map(f=><details key={f.question}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div></section><nav className="gf-service-related" aria-label="Related services">{page.slug!=="kickstarter-launch-services"?<Link href="/kickstarter-launch-services">Full launch services ↗</Link>:null}{page.slug!=="campaign-design"?<Link href="/campaign-design#pricing">Campaign design scope &amp; price ↗</Link>:null}{page.slug!=="gamefound-launch-services"?<Link href="/gamefound-launch-services">Gamefound launches ↗</Link>:null}{gameCategories.filter(g=>g.slug!==page.slug).map(g=><Link key={g.slug} href={`/${g.slug}`}>{g.name} ↗</Link>)}</nav></main><SeoFooter/></>;
}
