import { ResponsiveImage } from "./ResponsiveImage";
const mockups = [
  {image:"party-cards",title:"Party & family cards",style:"Risograph illustration",alt:"Snack Attack concept: colourful fruit characters on a party deck and box against a yellow backdrop",copy:"Big shapes, expressive characters and a box you can spot across the table."},
  {image:"adventure-cards",title:"Adventure card games",style:"Retro science fiction comics",alt:"Orbital Crew concept: comic book astronauts on a card game box with illustrated cards and tokens",copy:"Illustrated cards and a darker palette for a cooperative space adventure."},
  {image:"minimal-cards",title:"Abstract strategy decks",style:"Minimal geometric design",alt:"Common Ground concept: ivory cards with green and blue geometric shapes beside a compact green box",copy:"Quiet colours and simple geometry that leave room to read the cards."},
] as const;
export function MockupGallery() {
 return <section className="gf-section gf-mockups" id="mockups" aria-labelledby="mockups-title"><div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">Card game concepts</span><h2 id="mockups-title">Three styles of{" "}<br /><em>card game mockup.</em></h2></div><p>A few different directions for card games. Your own artwork sets the starting point for your campaign.</p></div><div className="gf-mockup-grid">{mockups.map(m=><figure className="gf-mockup-card" key={m.image} data-reveal><div className="gf-mockup-image"><ResponsiveImage src={`/images/campaign/${m.image}.webp`} alt={m.alt} width="1200" height="800" loading="lazy"/><span className="gf-concept-label glass">Concept mockup</span></div><figcaption><span className="gf-eyebrow">{m.style}</span><h3>{m.title}</h3><p>{m.copy}</p></figcaption></figure>)}</div><p className="gf-caption">These are original concepts, separate from the client campaigns in Past work.</p></section>;
}
