import { ResponsiveImage } from "./ResponsiveImage";
import {pastWork,clientTestimonials} from "../past-work";
export function PastWork({compact = false}: {compact?: boolean}) {
  return <section className={`gf-section gf-past-work${compact ? " gf-proof-compact" : ""}`} id="past-work" aria-labelledby="past-work-title">
    <div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">Past work</span><h2 id="past-work-title">{compact ? <>Real games.<br/><em>Real campaign work.</em></> : <>Tabletop Kickstarter{" "}<br /><em>campaigns I’ve worked on.</em></>}</h2></div>{!compact && <p>Creative work for three tabletop projects. Follow the links to see their published Kickstarter campaigns.</p>}</div>
    <div className="gf-work-grid">{pastWork.map(project=><article className="gf-work-card" key={project.name} data-reveal><div className="gf-work-image"><ResponsiveImage src={`/images/work/${project.image}.webp`} alt={project.alt} width="1200" height="675" loading="lazy" /></div><div className="gf-work-copy"><span className="gf-eyebrow">{project.category}</span><h3>{project.name}</h3><p className="gf-work-subtitle">{project.title}</p>{!compact && <p>{project.description}</p>}<a className="gf-text-link" href={project.href} target="_blank" rel="noopener noreferrer">View Kickstarter <span aria-hidden="true">↗</span><span className="gf-sr-only"> for {project.name} (opens in a new tab)</span></a><small>{project.imageNote}</small></div></article>)}</div>
  </section>;
}
export function ClientTestimonials({compact = false}: {compact?: boolean}) {
  return <section className={`gf-section gf-testimonials${compact ? " gf-quotes-compact" : ""}`} id="testimonials" aria-labelledby="testimonials-title"><div className={`gf-section-heading${compact ? " gf-sr-only" : ""}`} data-reveal><div><span className="gf-eyebrow">Client feedback</span><h2 id="testimonials-title">What campaign{" "}<br /><em>clients say.</em></h2></div><p>Client feedback on the creative work shown above.</p></div><div className="gf-quote-grid">{clientTestimonials.map(t=><figure className="gf-quote" key={t.project} data-reveal><span className="gf-quote-mark" aria-hidden="true">“</span><blockquote><p>{t.quote}</p></blockquote><figcaption><strong>{t.project}</strong><span>Client: {t.client}</span></figcaption></figure>)}</div></section>;
}
