import Link from "next/link";
import {notFound} from "next/navigation";
import {launchGuides,launchGuideDate} from "../../launch-guides";
import {pageMetadata} from "../../site-config";
import {SeoArticlePage,ArticleTable} from "../../components/SeoArticlePage";
export const dynamicParams=false;
export function generateStaticParams(){return launchGuides.map(g=>({slug:g.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const g=launchGuides.find(g=>g.slug===slug);if(!g)notFound();return pageMetadata({title:g.title,description:g.description,path:`/guides/${slug}`,kind:"article",publishedTime:launchGuideDate,modifiedTime:launchGuideDate});}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const g=launchGuides.find(g=>g.slug===slug);if(!g)notFound();return <SeoArticlePage slug={g.slug} title={g.title} description={g.description} category={g.tag} answer={g.answer} published={launchGuideDate} updated={launchGuideDate} readTime="5 min read" toc={g.sections.map(s=>({id:s.id,label:s.title}))} faqs={g.faqs} sources={g.sources}>{g.sections.map(s=><section key={s.id}><h2 id={s.id}>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.list&&<ul>{s.list.map(x=><li key={x}>{x}</li>)}</ul>}{s.table&&<ArticleTable caption={s.title} headers={s.table.headers} rows={s.table.rows}/>} {s.source!==undefined&&<p className="article-source-note">Source: <a href={g.sources[s.source].href}>{g.sources[s.source].label}</a>.</p>}</section>)}<aside className="article-callout"><strong>Planning a tabletop launch?</strong><p>Explore <Link href="/campaign-design">Guildframe campaign design</Link> or prepare your <Link href="/guides/what-to-send-kickstarter-campaign-designer">design brief</Link>. Start with a free mockup through the form below.</p></aside><nav className="gf-service-related" aria-label="Related launch guides">{launchGuides.filter(x=>x.slug!==g.slug).slice(0,3).map(x=><Link key={x.slug} href={`/guides/${x.slug}`}>{x.title} ↗</Link>)}</nav></SeoArticlePage>}
