export const campaignDate = "2026-10-03";
export const gameCategories = [
 {slug:"board-game-kickstarter-campaign-design",name:"Board games",tag:"Strategy, family & party games",image:"board-games",alt:"Original harbour strategy game beside a colourful abstract family game",copy:"Show a turn, lay out the components and explain what players are trying to do.",focus:"Strategy, family, party, cooperative and solo games",details:["A quick explanation of the main turn and the decisions players make","Component spreads that distinguish the base game from upgrades","Player count, play time, age guidance and language information","Reward comparisons for core games, deluxe editions and expansions"]},
 {slug:"card-game-kickstarter-campaign-design",name:"Card games & TCGs",tag:"Party decks, deckbuilders & TCGs",image:"card-games",alt:"Original space themed trading cards alongside bright food themed party cards",copy:"Show enough cards to explain the game, then make deck sizes and reward contents easy to compare.",focus:"Trading card games, party decks, deckbuilders and collectible games",details:["Legible sample cards with enough scale to understand their layout","A clear explanation of deck size, starter sets and how a round works","Edition and pack contents stated without implying unconfirmed rarity odds","Reward graphics that separate complete decks, bundles and optional extras"]},
 {slug:"ttrpg-kickstarter-campaign-design",name:"Tabletop RPGs",tag:"Rulebooks, adventures & zines",image:"ttrpgs",alt:"Original noir roleplaying hardback and cosmic horror zine with character sheets",copy:"Introduce the setting and the kind of session it offers, with sample pages people can read.",focus:"Core rulebooks, adventures, settings, supplements and indie zines",details:["The premise, intended play experience and whether a system is required","Readable interior spreads, character sheets and a route to sample material","Physical books, PDFs and bundles separated clearly in rewards","Accurate binding, format and production details supplied by the creator"]},
 {slug:"miniatures-kickstarter-campaign-design",name:"Miniatures & terrain",tag:"Physical models, terrain & STLs",image:"miniatures",alt:"Original science fiction mechs, woodland creatures and modular lunar terrain",copy:"Show the sculpts up close, with the scale and contents of each physical or digital set.",focus:"Physical miniatures, STL collections, terrain, skirmish kits and hobby sets",details:["Scale, dimensions and assembly information beside the product imagery","Clear distinctions between physical products and digital files","Labelled comparisons of sculpt sets, poses, terrain pieces and bundles","Creator supplied licence and printing information for digital collections"]},
 {slug:"tabletop-accessories-campaign-design",name:"Dice & accessories",tag:"Dice, storage & gaming accessories",image:"accessories",alt:"Original colourful dice, a coral dice tray, petrol card sleeves and mint tokens",copy:"Show the materials, dimensions and how the accessory fits into a game night.",focus:"Dice, trays, sleeves, tokens, organisers, gaming bags and storage",details:["Dimensions, materials and compatibility explained in everyday language","Useful close ups that show finishes and how the accessory is used","Colour and size choices shown consistently across reward tiers","Bundle contents and any game products shown for context distinguished"]},
] as const;
export const campaignFaqs = [
 {question:"What does Guildframe help with?",answer:"Planning, prelaunch pages and email, campaign copy and graphics, paid advertising and live campaign support. You can book a defined stage or a broader launch engagement. The proposal lists the work, owners, schedule and costs."},
 {question:"How much does a full launch cost?",answer:"Full launches are quoted after reviewing the game, assets, audience, launch date and support needs. The proposal separates service fees, ad spend, software and other provider costs. Campaign design is also available on its own; its fixed price is listed on the campaign design page."},
 {question:"Can I hire you just for design or ads?",answer:"Yes. You can book campaign creative, prelaunch preparation, paid advertising or live support separately. We agree where your existing team takes over and what Guildframe will deliver."},
 {question:"Do you work on Kickstarter and Gamefound?",answer:"Yes. Tell me which platform you plan to use, or ask for help comparing the work involved. The campaign is prepared for your chosen platform and checked there before launch."},
 {question:"Who manages the paid advertising?",answer:"Umair manages paid advertising at Guildframe. We agree the advertising channels, account access, test plan, spend limits and reporting before ads run. The media budget is separate from the service fee."},
 {question:"How does the free mockup work?",answer:"Share a short game description and usable artwork. I’ll review it and design one opening campaign section so you can see a direction before booking creative work. It is free to request, with no payment or obligation to book."},
 {question:"How early should I get in touch?",answer:"Once you can explain the game, share some artwork and discuss a possible launch date. If assets, rewards or production details are still changing, say so. We’ll check readiness and work out a schedule before promising a date."},
 {question:"What if my launch date is close?",answer:"Send the date, current page, assets and the work still missing. I’ll review what fits the time available before accepting the scope. A smaller, realistic brief is better than a schedule that leaves no time to check the campaign."},
 {question:"Do I keep my accounts, contacts and files?",answer:"Yes. The campaign and marketing accounts stay yours. We agree access and list the final files and editable sources in the brief. Email contacts are collected through your signup flow with clear permission to contact them."},
 {question:"Will you guarantee funding or a return on ads?",answer:"No. The game, price, audience, production costs and launch preparation all affect the outcome. We set a test plan and budget, report what the tracking can show and agree when to adjust or stop spending."},
 {question:"Do you handle manufacturing and shipping?",answer:"The launch service covers creative, marketing and the agreed campaign operations. You and your suppliers own manufacturing, freight, taxes and delivery. We can prepare backer updates and pledge-manager content around the facts you confirm."},
 {question:"What happens before I pay?",answer:"We review your project and agree the deliverables, fees, payment schedule, support period and revision process in writing. If you want a creative preview, request the free opening mockup first."},
] as const;

export const categoryFaqs: Record<string, {question:string;answer:string}[]> = {
 "board-game-kickstarter-campaign-design": [
  {question:"What board game artwork should I send?",answer:"Send the box art, component images and a short gameplay explanation. Include player count, play time, proposed rewards and any rules or preview links. Mark prototype images so they can be labelled correctly."},
  {question:"Can you compare a standard and deluxe edition?",answer:"Yes. Reward comparisons can show which components change and which expansions are included. You confirm the contents and prices; I use the same names across the copy and graphics."},
 ],
 "card-game-kickstarter-campaign-design": [
  {question:"Can you design a Kickstarter page for a TCG or party card game?",answer:"Yes. For a TCG, the page can explain the starter decks, sample cards and pack contents. For a party game, a sample round may explain the game in fewer steps. The copy and graphics use your confirmed card information."},
  {question:"Does campaign design include drawing new card artwork?",answer:"The campaign page uses your supplied card artwork. New card illustration and game design are separate work. The design brief covers campaign copy, page graphics and reward presentation."},
 ],
 "ttrpg-kickstarter-campaign-design": [
  {question:"Can the page show both print books and PDF rewards?",answer:"Yes. I label the physical and digital contents separately and show when a print book includes its PDF. You provide the confirmed format, page count, binding and bundle details."},
  {question:"What should I share for an RPG campaign mockup?",answer:"Send a short description of the game, the cover or usable artwork and any sample spread you can share. Say whether it is a complete system, adventure or supplement and what players need to use it."},
 ],
 "miniatures-kickstarter-campaign-design": [
  {question:"Can you present STL files and physical miniatures in one campaign?",answer:"Yes. The graphics label digital files and physical sets separately, with the scale, sculpt list and included pieces supplied by you. Licence and printing details should be confirmed before publication."},
  {question:"What images help explain modular terrain?",answer:"Show an assembled layout, the individual pieces and a scale reference. Connection details and different configurations help players understand what a set can build. Label anything shown for context that is not included."},
 ],
 "tabletop-accessories-campaign-design": [
  {question:"Do you design campaigns for deck boxes, sleeves and dice?",answer:"Yes. I use your product photos and measurements to explain storage, materials, dimensions and compatibility. Reward graphics can compare finishes, sizes and bundle contents."},
  {question:"How do you explain whether an accessory fits a game?",answer:"Use the dimensions and compatibility you have checked. Show the accessory in use and label cards, dice or games shown only for context. Avoid implying compatibility that has not been confirmed."},
 ],
 "gamefound-campaign-design": [
  {question:"Can I reuse my Kickstarter artwork for Gamefound?",answer:"Existing artwork and some copy can be reused. The page layout, story sections and reward graphics still need a check in the Gamefound editor and preview. Confirm the platform before agreeing the deliverables."},
  {question:"Who controls Gamefound prices, shipping and publication?",answer:"You control the project settings, rewards, prices, taxes, shipping and publication. I prepare the campaign copy and graphics and review how they display in the agreed preview."},
 ],
};
