export const campaignDate = "2026-09-30";
export const gameCategories = [
 {slug:"board-game-kickstarter-campaign-design",name:"Board games",tag:"Big ideas. Clear rules.",image:"board-games",alt:"Original harbour strategy game beside a colourful abstract family game",copy:"Show the play, the pieces and the reason it belongs on someone’s table.",focus:"Strategy, family, party, cooperative and solo games",details:["A quick explanation of the main turn and the decisions players make","Component spreads that distinguish the base game from upgrades","Player count, play time, age guidance and language information","Reward comparisons for core games, deluxe editions and expansions"]},
 {slug:"card-game-kickstarter-campaign-design",name:"Card games & TCGs",tag:"Make every card count.",image:"card-games",alt:"Original space themed trading cards alongside bright food themed party cards",copy:"From quick party decks to a new trading card system. Let people see what makes yours click.",focus:"Trading card games, party decks, deckbuilders and collectible games",details:["Legible sample cards with enough scale to understand their layout","A clear explanation of deck size, starter sets and how a round works","Edition and pack contents stated without implying unconfirmed rarity odds","Reward graphics that separate complete decks, bundles and optional extras"]},
 {slug:"ttrpg-kickstarter-campaign-design",name:"Tabletop RPGs",tag:"Open a new world.",image:"ttrpgs",alt:"Original noir roleplaying hardback and cosmic horror zine with character sheets",copy:"Books, zines, adventures and entire systems. Give the setting a voice and the book a proper introduction.",focus:"Core rulebooks, adventures, settings, supplements and indie zines",details:["The premise, intended play experience and whether a system is required","Readable interior spreads, character sheets and a route to sample material","Physical books, PDFs and bundles separated clearly in rewards","Accurate binding, format and production details supplied by the creator"]},
 {slug:"miniatures-kickstarter-campaign-design",name:"Miniatures & terrain",tag:"Small pieces. Big presence.",image:"miniatures",alt:"Original science fiction mechs, woodland creatures and modular lunar terrain",copy:"Science fiction armies, whimsical creatures or modular terrain. Show the detail and explain exactly what arrives.",focus:"Physical miniatures, STL collections, terrain, skirmish kits and hobby sets",details:["Scale, dimensions and assembly information beside the product imagery","Clear distinctions between physical products and digital files","Labelled comparisons of sculpt sets, poses, terrain pieces and bundles","Creator supplied licence and printing information for digital collections"]},
 {slug:"tabletop-accessories-campaign-design",name:"Dice & accessories",tag:"The extras become the star.",image:"accessories",alt:"Original colourful dice, a coral dice tray, petrol card sleeves and mint tokens",copy:"Dice, trays, tokens, sleeves and clever storage. Make the material, fit and finish easy to judge.",focus:"Dice, trays, sleeves, tokens, organisers, gaming bags and storage",details:["Dimensions, materials and compatibility explained in everyday language","Useful close ups that show finishes and how the accessory is used","Colour and size choices shown consistently across reward tiers","Bundle contents and any game products shown for context distinguished"]},
] as const;
export const campaignFaqs = [
 {question:"How much does campaign design cost?",answer:"Guildframe campaign design is $975 USD for one campaign. We agree the page sections, deliverables and schedule before work begins. Your platform fees, product production and advertising budget are separate."},
 {question:"What is included in the $975 campaign design?",answer:"Campaign page structure, copy shaped from your project information, a consistent visual direction, section graphics, reward comparisons and stretch goal graphics where your campaign needs them. The final deliverable list is confirmed in the brief. New game illustration, video production and paid advertising are quoted separately if needed."},
 {question:"Do you design for Kickstarter and Gamefound?",answer:"Yes. The design is prepared for the platform you choose, with its editor and page structure in mind. Tell us which platform you plan to use when requesting your mockup."},
 {question:"How does the free mockup work?",answer:"Send your project description and any artwork you can share. Guildframe reviews the material and creates a mockup of an opening campaign section to explore the direction. There is no payment or obligation to book the full project."},
 {question:"Can you work with a game that is still in development?",answer:"Yes, if there is enough artwork and a clear description to establish a direction. Mark unfinished components and unconfirmed production details in your brief. The campaign should only present claims you are ready to stand behind."},
 {question:"Will campaign design guarantee funding?",answer:"No. A clear page helps people understand your project, but demand, pricing, audience, launch preparation and delivery confidence also affect a campaign. Guildframe does not promise a funding result."},
] as const;
