import type { CampaignPage } from "./components/CampaignServicePage";

export const launchServices: CampaignPage[] = [
  {
    slug: "kickstarter-launch-services", title: "Kickstarter Launch Services for Tabletop Games",
    description: "Plan and launch your tabletop Kickstarter with Guildframe. Prelaunch pages, campaign design, email, paid advertising and campaign management in one scope.",
    headline: "Kickstarter launch services", accent: "for tabletop creators.", image: "launch-studio",
    alt: "Concept board game, party cards, botanical trading cards, RPG books and miniatures on a petrol tabletop",
    introTitle: "Get the launch work in one place.",
    intro: "You have a game to finish and a campaign to run. Guildframe brings the planning, creative and marketing together so your landing page, emails, ads and campaign tell the same story. Work directly with Umair from the first brief through the agreed launch period.",
    details: ["Positioning, an asset review and a launch schedule with named responsibilities", "A prelaunch landing page, signup flow, email sequence and tracking setup", "Campaign copy, gameplay graphics, component images and reward comparisons", "Paid advertising with creative tests, a separate media budget and agreed reporting", "Launch emails, campaign updates, FAQ maintenance and live creative support", "A post-campaign communication and pledge-manager handoff when included"],
    secondTitle: "Start with the work your campaign needs.",
    secondCopy: "A first-time publisher may need the whole launch planned. An established studio may already have an audience and only need creative or live support. Send your project, current assets and target date. The proposal lists what Guildframe will deliver, the support period, fees and costs paid to other providers. You approve the product details, rewards and spending before anything is published.",
    guide: "board-game-kickstarter-marketing-plan", guideTitle: "Build your board game Kickstarter marketing plan", kind: "launch",
  },
  {
    slug: "kickstarter-prelaunch-marketing", title: "Kickstarter Prelaunch Marketing for Board Games",
    description: "Prepare your board game Kickstarter audience with a landing page, signup flow, email sequence, tracking and paid creative tests. Get a scoped proposal.",
    headline: "Kickstarter prelaunch marketing", accent: "before funding opens.", image: "party-cards",
    alt: "Colourful party card game concept with a small box and illustrated cards",
    introTitle: "Give interested players a reason to follow along.",
    intro: "A launch announcement works better when people already understand the game. We build a prelaunch page around what players do, collect permission to email interested visitors and plan useful messages before launch. The page, emails and ads use the same artwork and confirmed offer.",
    details: ["An audience and positioning brief based on your game and playtest feedback", "Landing page copy, design and a signup flow in your own accounts", "A welcome email and prelaunch sequence showing gameplay, samples and the launch date", "Analytics, campaign link naming and test submissions before traffic starts", "Paid creative tests with spend limits approved in advance", "A launch readiness review based on engagement, economics and the finished campaign"],
    secondTitle: "An email signup is a starting point.",
    secondCopy: "We report what happened after a visitor signed up: whether messages reached them, which links they used and what your tracking can show. A cheap lead is not automatically a future backer. Your existing audience, budget, available artwork and target date shape the test plan. Email software and ad spend are listed separately from the service fee, and your accounts and contacts stay yours.",
    guide: "kickstarter-prelaunch-email-list", guideTitle: "Plan a prelaunch email list and launch sequence", kind: "launch",
  },
  {
    slug: "kickstarter-advertising", title: "Kickstarter Advertising for Board Games & TTRPGs",
    description: "Guildframe manages paid advertising for tabletop Kickstarter campaigns. Get creative tests, tracking, budget controls and reporting on spend and pledges.",
    headline: "Kickstarter advertising", accent: "for your tabletop launch.", image: "card-games",
    alt: "Space themed trading card concept beside colourful party cards",
    introTitle: "Test the message before you increase the budget.",
    intro: "Umair handles paid advertising at Guildframe. The work starts with the game, offer and campaign economics, then moves into creative tests and an agreed media plan. We can advertise before launch to build an audience and during the campaign to reach potential backers.",
    details: ["An account, audience and tracking review before running ads", "Ad copy and creative variants built around gameplay, the product and rewards", "Campaign setup and management on the advertising channels agreed in your scope", "A test budget, spend limits and approval rules before scaling", "Reporting on spend, leads and attributable pledges where tracking is available", "Creative changes and campaign adjustments informed by the results"],
    secondTitle: "Keep the media budget separate.",
    secondCopy: "The proposal separates Guildframe's management fee from money spent on ads. We agree which accounts will run the campaign, how spending changes are approved and which reporting sources we use. Platform reports can differ, so we explain the attribution window and avoid counting the same pledge twice. Funding, profit and ad returns depend on the offer, audience and costs; they are not guaranteed.",
    guide: "kickstarter-advertising-budget-board-games", guideTitle: "Work out a Kickstarter advertising test budget", kind: "launch",
  },
  {
    slug: "kickstarter-campaign-management", title: "Kickstarter Campaign Management for Tabletop Games",
    description: "Get tabletop Kickstarter launch checks, emails, backer updates, FAQ maintenance and creative support. Agree your campaign support period with Guildframe.",
    headline: "Kickstarter campaign management", accent: "from launch to close.", image: "board-games",
    alt: "Harbour strategy board game concept with wooden pieces and a colourful family game",
    introTitle: "Have the updates ready before the questions arrive.",
    intro: "Launching is only the start of the live campaign. Rewards change, questions repeat and new milestones need clear communication. Guildframe plans the launch day tasks and supports the campaign through an agreed period, with a review process for updates and spending.",
    details: ["A final review of the campaign page, rewards, links and mobile presentation", "A launch day checklist with a named publisher and approval process", "Launch and reminder emails for your permission-based audience", "Draft backer updates, FAQ answers and responses to recurring questions", "Reward or stretch goal graphics when changes are approved", "Scheduled campaign reporting and a close-of-campaign handoff"],
    secondTitle: "Know who approves each change.",
    secondCopy: "Before launch, we agree the support dates, working hours, response expectations and who publishes each update. You confirm manufacturing, shipping, taxes, delivery estimates and reward changes. We turn those facts into clear communication. Ad management can be included with a separate media budget. After the campaign, you receive the agreed assets, reports and a list of outstanding tasks.",
    guide: "kickstarter-live-campaign-updates", guideTitle: "Plan your live campaign updates and support", kind: "launch",
  },
  {
    slug: "gamefound-launch-services", title: "Gamefound Launch Services for Tabletop Creators",
    description: "Prepare a tabletop Gamefound launch with campaign creative, prelaunch email, paid advertising and live support. Get a platform-specific scope from Guildframe.",
    headline: "Gamefound launch services", accent: "for games, books & miniatures.", image: "miniatures",
    alt: "Science fiction miniature concept, woodland models and modular lunar terrain",
    introTitle: "Plan around how Gamefound presents your project.",
    intro: "Gamefound separates the story, rewards and campaign stages. We plan the creative and communication around that structure, so the same names, contents and promises appear across your story, reward images, emails and ads. Your project settings stay in your account.",
    details: ["A launch plan based on your project stage and Gamefound setup", "Story copy, section graphics and clear physical or digital reward comparisons", "Prelaunch landing and email work where your plan needs it", "Paid advertising with approved spend limits and reporting sources", "A review in the platform preview or tester workflow before publication", "Launch updates and late-pledge or pledge-manager communication when scoped"],
    secondTitle: "Confirm platform setup before campaign production.",
    secondCopy: "Share the project link, account status, products and proposed rewards. We check what is ready and what needs confirmation before design or ads begin. You own the reward prices, taxes, shipping rules and publication decision. Guildframe prepares the agreed creative, marketing and campaign support. Platform fees and production costs sit outside the service fee and belong in your campaign budget.",
    guide: "gamefound-launch-page-checklist", guideTitle: "Check your Gamefound page before launch", kind: "launch",
  },
  {
    slug: "post-campaign-support", title: "Post Campaign Support for Funded Tabletop Games",
    description: "Plan your tabletop campaign handoff with backer updates, pledge manager content, late pledge assets and optional storefront setup. Scope it with Guildframe.",
    headline: "After the campaign", accent: "keep backers informed.", image: "ttrpgs",
    alt: "Noir RPG hardback and cosmic horror zine concepts with character sheets",
    introTitle: "Turn the next steps into a clear handoff.",
    intro: "A funded campaign still needs accurate updates, reward information and a plan for new orders. Guildframe helps prepare the communication and content for your pledge manager, late pledges or storefront. The scope follows your production and fulfilment plan.",
    details: ["A campaign close update and schedule for future backer communication", "Reward names, product descriptions and graphics for the chosen pledge manager", "A review of survey wording and late-pledge product presentation", "Updated images and copy when final product details change", "Optional Shopify store planning and setup under a separate brief", "An asset and account handoff with named owners for the remaining tasks"],
    secondTitle: "Production facts come from your production team.",
    secondCopy: "You or your suppliers confirm manufacturing progress, shipping charges, tax treatment and delivery estimates. We help communicate those facts and organise the agreed platform content. Manufacturing, freight, customs and physical fulfilment require their own suppliers and budgets. Share your existing plan so the communication supports what can actually be delivered.",
    guide: "what-happens-after-kickstarter-is-funded", guideTitle: "Understand what happens after Kickstarter funding", kind: "launch",
  },
];

export const serviceCards = [
  { href: "/kickstarter-prelaunch-marketing", number: "01", title: "Prelaunch marketing", copy: "Landing pages, email and audience tests before the campaign opens.", tag: "Build interest" },
  { href: "/campaign-design", number: "02", title: "Campaign creative", copy: "Copy, gameplay graphics and rewards that explain what you're making.", tag: "Show the game" },
  { href: "/kickstarter-advertising", number: "03", title: "Paid advertising", copy: "Creative tests, campaign management and reporting with a separate ad budget.", tag: "Reach backers" },
  { href: "/kickstarter-campaign-management", number: "04", title: "Launch support", copy: "Launch checks, emails, updates and a clear handoff after the campaign.", tag: "Run the campaign" },
];
