import Link from "next/link";
import {SeoHeader,SeoFooter} from "./components/SeoChrome";
import {JsonLd} from "./components/JsonLd";
import {absoluteUrl} from "./site-config";
import {campaignFaqs,gameCategories,campaignDate} from "./campaign-content";
export default function Home(){return <>
 <JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":absoluteUrl("/"),url:absoluteUrl("/"),name:"Kickstarter Campaign Design for Tabletop Games",dateModified:campaignDate,isPartOf:{"@id":absoluteUrl("/#website")}},{"@type":"Service","@id":absoluteUrl("/campaign-design#service"),name:"Tabletop crowdfunding campaign design",serviceType:"Kickstarter and Gamefound campaign design",provider:{"@id":absoluteUrl("/#organization")},url:absoluteUrl("/campaign-design"),offers:{"@type":"Offer",price:"975",priceCurrency:"USD",url:absoluteUrl("/campaign-design")}},{"@type":"FAQPage",mainEntity:campaignFaqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}]}}/>
 <a className="skip-link" href="#main-content">Skip to content</a><SeoHeader/>
 <main id="main-content" className="gf-home">
  <section className="gf-hero"><div className="gf-hero-copy"><span className="gf-eyebrow"><span className="gf-status-dot"/>Kickstarter &amp; Gamefound campaign design</span><h1>Good games.<br /><em>Great first<br className="gf-desktop-break" /> impressions.</em></h1><p>You have made the game. Let’s make a campaign that helps people see it, understand it and want it on their table.</p><div className="gf-actions"><a className="gf-button" href="#start-project">Get my free mockup <span aria-hidden="true">↗</span></a><a className="gf-text-link" href="#pricing">Campaign design · $975 <span aria-hidden="true">↘</span></a></div><div className="gf-hero-note"><span>For the whole tabletop.</span><span>Made around your game.</span></div></div>
   <div className="gf-hero-visual"><img className="gf-hero-image" src="/images/campaign/hero.webp" alt="An original strategy game, illustrated card deck, roleplaying books, science fiction miniatures and colourful dice arranged together" width="1774" height="887" fetchPriority="high"/><div className="gf-visual-tag glass"><span className="gf-tag-dot"/>Your next adventure starts here.</div><div className="gf-visual-bottom glass"><span>Small studio.<br /><strong>Big tabletop energy.</strong></span><span className="gf-tag-arrow" aria-hidden="true">↗</span></div></div>
  </section>
  <div className="gf-ticker" aria-label="Games we design campaigns for"><span>Board games</span><i aria-hidden="true">✳</i><span>Card games</span><i aria-hidden="true">✳</i><span>Tabletop RPGs</span><i aria-hidden="true">✳</i><span>Miniatures</span><i aria-hidden="true">✳</i><span>Dice &amp; accessories</span></div>
  <section className="gf-section gf-intro" data-reveal><span className="gf-eyebrow">The game is yours. The introduction is our job.</span><div className="gf-intro-grid"><h2>A page that makes<br /><em>the pieces fit.</em></h2><p>Great art gets attention. A great campaign also answers the questions: What is this? How does it play? What do I get? We bring the story, graphics and rewards into one clear, scrollable page.</p></div><div className="gf-feature-grid"><article><span className="gf-number">01</span><h3>Find the story</h3><p>A strong opening, a useful page order and copy that sounds like your game.</p></article><article><span className="gf-number">02</span><h3>Show the good stuff</h3><p>Artwork, components and gameplay presented with room to breathe.</p></article><article><span className="gf-number">03</span><h3>Make choosing easier</h3><p>Reward comparisons and stretch goal graphics people can actually follow.</p></article></div></section>
  <section className="gf-section gf-games" id="games"><div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">One studio. Plenty of worlds.</span><h2>Whatever you bring<br /><em>to the table.</em></h2></div><p>A cosy family game deserves its own look. So does a grim science fiction skirmish. Your campaign should feel like your game.</p></div><div className="gf-game-grid">{gameCategories.map((g,i)=><Link href={`/${g.slug}`} key={g.slug} className={`gf-game-card gf-game-${i}`} data-reveal><div className="gf-game-image"><img src={`/images/campaign/${g.image}.webp`} alt={g.alt} width="1000" height="750" loading="lazy"/></div><div className="gf-game-copy"><span className="gf-eyebrow">{g.tag}</span><h3>{g.name}<span aria-hidden="true">↗</span></h3><p>{g.copy}</p></div></Link>)}</div><p className="gf-caption">Original concept imagery, created to show the range of projects Guildframe can design for.</p></section>
  <section className="gf-section gf-process" id="process"><div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">No mystery. Just a good process.</span><h2>From your idea<br /><em>to your campaign.</em></h2></div><p>Start with a free look at the direction. Book the full campaign when the fit feels right.</p></div><ol className="gf-process-list">{[{title:"Tell me about your game",copy:"Share the premise, artwork, campaign platform and the launch date you have in mind."},{title:"See a free mockup",copy:"An opening section gives you a feel for the visual direction before you commit."},{title:"Agree the full brief",copy:"We confirm the sections, deliverables and schedule for your $975 campaign."},{title:"Bring the page together",copy:"Story, graphics and rewards take shape, then we review the final work before your launch."}].map((step,i)=><li key={step.title} data-reveal><span className="gf-process-index">0{i+1}</span><h3>{step.title}</h3><p>{step.copy}</p></li>)}</ol></section>
  <section className="gf-section gf-pricing" id="pricing" data-reveal><div className="gf-pricing-copy"><span className="gf-eyebrow">One campaign. A clear starting point.</span><h2>Your game.<br />A proper campaign.<br /><em>$975.</em></h2><p>Campaign page design for Kickstarter or Gamefound, built around the artwork and project details you provide.</p><Link className="gf-text-link" href="/campaign-design">See the full service <span aria-hidden="true">↗</span></Link></div><div className="gf-price-card glass"><span className="gf-eyebrow">Campaign design</span><div className="gf-price">$975 <span>USD / campaign</span></div><ul><li>Page structure &amp; campaign copy</li><li>Visual direction &amp; section graphics</li><li>Gameplay &amp; component presentation</li><li>Reward comparisons</li><li>Stretch goal graphics where needed</li><li>Files prepared for your chosen platform</li></ul><a className="gf-button" href="#start-project">Start with a free mockup <span aria-hidden="true">↗</span></a><p>We agree the exact deliverables and schedule before starting. New game illustration, video and advertising are separate.</p></div></section>
  <section className="gf-section gf-guides" data-reveal><div className="gf-section-heading"><div><span className="gf-eyebrow">A little less guesswork.</span><h2>Before you hit<br /><em>launch.</em></h2></div><Link className="gf-text-link" href="/guides">All launch guides ↗</Link></div><div className="gf-guide-grid">{[{path:"board-game-kickstarter-page-checklist",label:"Launch preparation",title:"Is your campaign page ready?",copy:"The practical checklist for a board game Kickstarter page."},{path:"board-game-kickstarter-campaign-design-cost",label:"Budget planning",title:"What should you budget for design?",copy:"Scope, assets and the actual $975 Guildframe offer."},{path:"what-to-send-kickstarter-campaign-designer",label:"Your design brief",title:"What does your designer need?",copy:"A useful asset handoff, without the giant folder hunt."}].map(g=><Link className="gf-guide-card" href={`/guides/${g.path}`} key={g.path}><span className="gf-eyebrow">{g.label}</span><h3>{g.title}</h3><p>{g.copy}</p><span className="gf-guide-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
  <section className="gf-section gf-faq" id="faq" data-reveal><div><span className="gf-eyebrow">The things you might be wondering.</span><h2>A few<br /><em>quick answers.</em></h2></div><div>{campaignFaqs.map(f=><details key={f.question}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div></section>
 </main><SeoFooter/>
 </>}
