import Link from "next/link";
import {SeoHeader,SeoFooter} from "./components/SeoChrome";
import {JsonLd} from "./components/JsonLd";
import {absoluteUrl} from "./site-config";
import {campaignService} from "./seo-entities";
import {PastWork,ClientTestimonials} from "./components/PastWork";
import {CampaignProcess} from "./components/CampaignProcess";
import {MockupGallery} from "./components/MockupGallery";
import {campaignFaqs,gameCategories,campaignDate} from "./campaign-content";
export default function Home(){return <>
 <JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":absoluteUrl("/"),url:absoluteUrl("/"),name:"Kickstarter Page Design for Tabletop Games",description:"Campaign page copy and graphics for $975 USD, with a free opening mockup.",inLanguage:"en",mainEntity:{"@id":absoluteUrl("/campaign-design#service")},dateModified:campaignDate,isPartOf:{"@id":absoluteUrl("/#website")}},campaignService(),{"@type":"FAQPage",mainEntity:campaignFaqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}]}}/>
 <a className="skip-link" href="#main-content">Skip to content</a><SeoHeader/>
 <main id="main-content" className="gf-home">
  <section className="gf-hero"><div className="gf-hero-copy"><span className="gf-eyebrow"><span className="gf-status-dot"/>Kickstarter &amp; Gamefound campaign design</span><h1>Kickstarter page design{" "}<br /><em>for your{" "}<br className="gf-desktop-break" /> tabletop game.</em></h1><p>I write your campaign copy and design the page graphics for Kickstarter or Gamefound. For $975, get a page that explains your game, shows what’s included and makes the rewards easy to compare. Start with a free opening mockup.</p><div className="gf-actions"><a className="gf-button" href="#start-project" data-analytics-event="service_interest" data-analytics-label="Free opening mockup" data-analytics-location="homepage">Get my free mockup <span aria-hidden="true">↗</span></a><a className="gf-text-link" href="#pricing" data-analytics-event="service_interest" data-analytics-label="Campaign design pricing" data-analytics-location="homepage">Campaign design · $975 <span aria-hidden="true">↘</span></a></div><div className="gf-hero-note"><span>Board games, cards, RPGs & more</span><span>$975 USD per campaign</span></div></div>
   <div className="gf-hero-visual"><img className="gf-hero-image" src="/images/campaign/hero.webp" alt="An original strategy game, illustrated card deck, roleplaying books, science fiction miniatures and colourful dice arranged together" width="1774" height="887" fetchPriority="high"/><div className="gf-visual-tag glass"><span className="gf-tag-dot"/>Designed around your game</div><div className="gf-visual-bottom glass"><span>Campaign copy &amp; graphics<br /><strong>From the first section to the rewards.</strong></span><span className="gf-tag-arrow" aria-hidden="true">↗</span></div></div>
  </section>
  <div className="gf-ticker" aria-label="Games we design campaigns for"><span>Board games</span><i aria-hidden="true">✳</i><span>Card games</span><i aria-hidden="true">✳</i><span>Tabletop RPGs</span><i aria-hidden="true">✳</i><span>Miniatures</span><i aria-hidden="true">✳</i><span>Dice &amp; accessories</span></div>
  <section className="gf-section gf-intro" data-reveal><span className="gf-eyebrow">What I can help with</span><div className="gf-intro-grid"><h2>Campaign copy,{" "}<br /><em>gameplay &amp; reward graphics.</em></h2><p>I use your artwork and project notes to build the page from the opening section through to the rewards. Backers can see how the game plays, what comes in the box and which edition suits them.</p></div><div className="gf-feature-grid"><article><span className="gf-number">01</span><h3>Campaign copy</h3><p>An opening that explains the idea, followed by the details people need before backing.</p></article><article><span className="gf-number">02</span><h3>Game & component graphics</h3><p>Your artwork, a sample turn and the contents of the box, with captions people can read.</p></article><article><span className="gf-number">03</span><h3>Reward comparisons</h3><p>Show which edition includes the expansion, the upgraded pieces or the PDF.</p></article></div></section>
  <PastWork/><ClientTestimonials/>
  <section className="gf-section gf-games" id="games"><div className="gf-section-heading" data-reveal><div><span className="gf-eyebrow">Games & tabletop projects</span><h2>Page design for{" "}<br /><em>every kind of tabletop game.</em></h2></div><p>A quick party deck needs a different page from a tactical miniatures game. The artwork, type and layout should suit what you’re making.</p></div><div className="gf-game-grid">{gameCategories.map((g,i)=><Link href={`/${g.slug}`} key={g.slug} className={`gf-game-card gf-game-${i}`} data-reveal><div className="gf-game-image"><img src={`/images/campaign/${g.image}.webp`} alt={g.alt} width="1000" height="750" loading="lazy"/></div><div className="gf-game-copy"><span className="gf-eyebrow">{g.tag}</span><h3>{g.name}<span aria-hidden="true">↗</span></h3><p>{g.copy}</p></div></Link>)}</div><p className="gf-caption">Concept mockups showing different types of tabletop projects.</p></section>
  <MockupGallery/>
  <CampaignProcess/>
  <section className="gf-section gf-pricing" id="pricing" data-reveal><div className="gf-pricing-copy"><span className="gf-eyebrow">Campaign design pricing</span><h2>Your campaign page,<br /><em>designed for $975.</em></h2><p>The $975 package covers campaign copy and page graphics using your existing artwork. We’ll agree the deliverables before work starts.</p><Link className="gf-text-link" href="/campaign-design">See the full service <span aria-hidden="true">↗</span></Link></div><div className="gf-price-card glass"><span className="gf-eyebrow">Campaign design</span><div className="gf-price">$975 <span>USD / campaign</span></div><ul><li>Page structure &amp; campaign copy</li><li>Visual direction &amp; section graphics</li><li>Gameplay &amp; component presentation</li><li>Reward comparisons</li><li>Stretch goal graphics where needed</li><li>Files prepared for your chosen platform</li></ul><a className="gf-button" href="#start-project" data-analytics-event="service_interest" data-analytics-label="Free opening mockup" data-analytics-location="homepage">Start with a free mockup <span aria-hidden="true">↗</span></a><p>The brief confirms the scope and schedule. Budget separately for new game illustration, video and advertising.</p></div></section>
  <section className="gf-section gf-guides" data-reveal><div className="gf-section-heading"><div><span className="gf-eyebrow">Planning your launch</span><h2>Plan your Kickstarter{" "}<br /><em>page before launch.</em></h2></div><Link className="gf-text-link" href="/guides">All launch guides ↗</Link></div><div className="gf-guide-grid">{[{path:"board-game-kickstarter-page-checklist",label:"Launch preparation",title:"Board game Kickstarter page checklist",copy:"The practical checklist for a board game Kickstarter page."},{path:"board-game-kickstarter-campaign-design-cost",label:"Budget planning",title:"How much does campaign design cost?",copy:"What the $975 package covers and what to budget for separately."},{path:"what-to-send-kickstarter-campaign-designer",label:"Your design brief",title:"What to send your campaign designer",copy:"The files and project details to send before design starts."}].map(g=><Link className="gf-guide-card" href={`/guides/${g.path}`} key={g.path}><span className="gf-eyebrow">{g.label}</span><h3>{g.title}</h3><p>{g.copy}</p><span className="gf-guide-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
  <section className="gf-section gf-faq" id="faq" data-reveal><div><span className="gf-eyebrow">Campaign design FAQ</span><h2>Campaign design{" "}<br /><em>questions, answered.</em></h2></div><div>{campaignFaqs.map(f=><details key={f.question}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div></section>
 </main><SeoFooter/>
 </>}
