import Link from "next/link";
import { SeoArticlePage, ArticleTable } from "../../components/SeoArticlePage";
import { pageMetadata } from "../../site-config";

const path = "/resources/tabletop-campaign-launch-worksheet";
const title = "Tabletop Campaign Launch Worksheet";
const description = "Collect your game facts, artwork, rewards, shipping plan and final campaign checks in one reusable Kickstarter or Gamefound worksheet.";
export const metadata = pageMetadata({ title, description, path, kind: "article", publishedTime: "2026-10-03", modifiedTime: "2026-10-03" });
export default function Page() {
  return <SeoArticlePage slug="tabletop-campaign-launch-worksheet" path={path} collectionLabel="Resources" collectionHref="/resources" schemaType="TechArticle" category="Campaign planning" title={title} description={description} answer="Fill in the worksheet with confirmed product facts before briefing a designer or assembling your campaign. Record what is final, what may change and who approves each decision. Use the same reward list for the graphics, story and native platform settings." published="2026-10-03" updated="2026-10-03" readTime="4 min read" toc={[{id:"download",label:"Download the worksheet"},{id:"facts",label:"Game and product facts"},{id:"rewards",label:"Rewards and shipping"},{id:"launch",label:"Final launch checks"}]} sources={[{label:"What to share on a project page",publisher:"Kickstarter",href:"https://help.kickstarter.com/en-us/articles/16236738-what-information-should-i-share-on-my-project-page"},{label:"Getting started with crowdfunding",publisher:"Gamefound",href:"https://help.gamefound.com/article/285-getting-started-with-crowdfunding"}]} faqs={[{question:"Can I use this for a card game or RPG?",answer:"Yes. Replace the product details with your own. Record deck contents for card games, supported systems and print/PDF formats for RPGs, and physical/file formats for miniatures."},{question:"Does filling in the worksheet confirm platform approval?",answer:"No. It organizes the brief and review. The creator still completes the platform's account, review, reward and launch requirements."},{question:"Can I send the completed worksheet to Guildframe?",answer:"Yes. Share the completed file and artwork link through the free mockup form or email umair@guildframe.com. The free mockup covers an opening campaign section."}]}>
    <h2 id="download">Download and fill it in with your team</h2>
    <p>The worksheet is a plain Markdown file. Open it in a text editor or copy its headings into your own document. It contains fields for the brief and a final launch checklist.</p>
    <p><a className="seo-button" href="/downloads/tabletop-campaign-launch-worksheet.md" download>Download the launch worksheet</a></p>
    <h2 id="facts">Gather the facts and label the assets</h2>
    <p>Write down what the reader needs to understand: what the product is, how it is played or used, who it suits and what comes with it. Name any required base game, supported system, companion app or other dependency.</p>
    <p>For every image, record whether it shows a render, prototype, test print, production sample or final artwork. Include the owner and permitted use. That avoids a designer presenting an unfinished component as final.</p>
    <ArticleTable caption="Adapt the brief to your product" headers={["Project","Details to include"]} rows={[["Board game","Players, duration, modes, box contents and rules"],["Card game or TCG","Deck and pack counts, readable sample cards, fixed or random contents"],["Tabletop RPG","Supported system, print/PDF formats, sample pages and required books"],["Miniatures or terrain","Physical or file format, quantities, scale, material and assembly state"],["Dice or accessories","Dimensions, compatibility, quantities and actual included pieces"]]} />
    <h2 id="rewards">Use one reward inventory</h2>
    <p>Record each tier&apos;s exact product names, quantities, format and price. Separate included products from optional extras. Give the same approved list to everyone writing copy, designing graphics or editing the platform rewards.</p>
    <p>Collect the shipping destinations, approved estimates and collection timing from the person handling fulfilment. Record quote dates and assumptions. Keep production, shipment and estimated arrival separate.</p>
    <p>Use the <Link href="/guides/kickstarter-reward-tier-graphics">reward graphics guide</Link> for comparisons and the <Link href="/guides/kickstarter-shipping-delivery-page">shipping guide</Link> for collection wording.</p>
    <h2 id="launch">Check the assembled platform page</h2>
    <ul className="article-checklist"><li>A new reader can explain the gameplay or product use.</li><li>Rules, review and video links work without private access.</li><li>Native rewards and graphics agree on contents and optional extras.</li><li>Prototype and render labels appear beside the images.</li><li>Shipping timing and reward delivery estimates match the story.</li><li>The actual mobile view is readable.</li><li>Stage publication and public visibility have been checked.</li><li>The creator has approved the final page and assigned the launch action.</li></ul>
    <p>For the platform checks, use the <Link href="/guides/kickstarter-review-launch-timeline">Kickstarter review-to-launch guide</Link> or the <Link href="/guides/gamefound-launch-page-checklist">Gamefound launch checklist</Link>.</p>
  </SeoArticlePage>;
}
